### ISSUE TITLE
On the Service Output Table add Pluggable Database Column 

### ISSUE THREAD

**Issue by ghost** [freddenis/oracle-scripts#11]
For rac-status.sh script:

Add Column PDB to display Pluggable Database for Service and if you filter Output on ServiceName also show DB Name for each column.

|CDB|PDB|Service|Nodes.....

**Comment by freddenis** [comment]
Hi,

rac-status is based on information from CRS/GI. CRS/GI has no knowledge about what is a PBD so this cannot be done as of now.

But ... GI 20c is supposed to include this as a new feature so as soon as GI 20c is available, I will have a look to implement this.

Regards,

Fred

**Comment by freddenis** [comment]
> For rac-status.sh script:
> 
> Add Column PDB to display Pluggable Database for Service and if you filter Output on ServiceName also show DB Name for each column.
> 
> |CDB|PDB|Service|Nodes.....

This has been implemented.
