### ISSUE TITLE
lspatches.sh fails with Error 41 

### ISSUE THREAD

**Issue by Project-42** [freddenis/oracle-scripts#12]
Having this issue in a 2 nodes RAC system (no Exadata)
Opatch is 12.2.0.1.21

-- Full error output:
```
[oracle@rac1-node1 scripts]$ ./lspatches.sh
Proceeding with /u01/app/19.3.0/grid . . .                                        Error 41
Proceeding with /u01/app/oracle/product/11.2.0/dbhome_1 . . .                     Error 41print() on closed filehandle $FileHandler at /u01/app/oracle/product/11.2.0/dbhome_1/OPatch/auto/database/bin/module/DBUtilServices.pm line 508.

Proceeding with /u01/app/oracle/product/12.1.0/dbhome_1 . . .                     Error 41print() on closed filehandle $FileHandler at /u01/app/oracle/product/12.1.0/dbhome_1/OPatch/auto/database/bin/module/DBUtilServices.pm line 508.

Proceeding with /u01/app/oracle/product/12.2.0/dbhome_1 . . .                     Error 41print() on closed filehandle $FileHandler at /u01/app/oracle/product/12.2.0/dbhome_1/OPatch/auto/database/bin/module/DBUtilServices.pm line 508.

Proceeding with /u01/app/oracle/product/18.0.0/dbhome_1 . . .                     Error 41print() on closed filehandle $FileHandler at /u01/app/oracle/product/18.0.0/dbhome_1/OPatch/auto/database/bin/module/DBUtilServices.pm line 508.

Proceeding with /u01/app/oracle/product/19.3.0/dbhome_1 . . .                     Error 41

[oracle@rac1-node1 scripts]$ 
```
-- If I force local, works fine, so wondering something fails in my "cluster inventory" (ssh keys are shared):
```
[oracle@rac1-node1 scripts]$ ./lspatches.sh -l
Proceeding with /u01/app/19.3.0/grid . . .                                        OK      
Proceeding with /u01/app/oracle/product/11.2.0/dbhome_1 . . .                     OK      
Proceeding with /u01/app/oracle/product/12.1.0/dbhome_1 . . .                     OK      
Proceeding with /u01/app/oracle/product/12.2.0/dbhome_1 . . .                     OK      
Proceeding with /u01/app/oracle/product/18.0.0/dbhome_1 . . .                     OK      
Proceeding with /u01/app/oracle/product/19.3.0/dbhome_1 . . .                     OK      

  /u01/app/19.3.0/grid  (opatch version 12.2.0.1.21)
------------------------------
  Patch ID  |   rac1-node1   |
------------------------------
  29401763  |        -       |
  29517242  |        -       |
  29517247  |        -       |
  29585399  |        -       |
------------------------------

  /u01/app/oracle/product/11.2.0/dbhome_1  (opatch version 12.2.0.1.21)
------------------------------
  Patch ID  |   rac1-node1   |
------------------------------
     No patch installed      |
------------------------------

  /u01/app/oracle/product/12.1.0/dbhome_1  (opatch version 12.2.0.1.21)
------------------------------
  Patch ID  |   rac1-node1   |
------------------------------
     No patch installed      |
------------------------------

  /u01/app/oracle/product/12.2.0/dbhome_1  (opatch version 12.2.0.1.21)
------------------------------
  Patch ID  |   rac1-node1   |
------------------------------
  26327418  |        -       |
------------------------------

  /u01/app/oracle/product/18.0.0/dbhome_1  (opatch version 12.2.0.1.21)
------------------------------
  Patch ID  |   rac1-node1   |
------------------------------
  27908644  |        -       |
  27923415  |        -       |
  28090523  |        -       |
  28090553  |        -       |
------------------------------

  /u01/app/oracle/product/19.3.0/dbhome_1  (opatch version 12.2.0.1.21)
------------------------------
  Patch ID  |   rac1-node1   |
------------------------------
  29517242  |        -       |
  29585399  |        -       |
------------------------------

[oracle@rac1-node1 scripts]$
```

-- ASM inventory example

```
[oracle@rac1-node1 ~]$ . oraenv
ORACLE_SID = [oracle] ? +ASM1
The Oracle base has been set to /u01/app/grid
[oracle@rac1-node1 ~]$ $ORACLE_HOME/OPatch/opatch lsinventory
Oracle Interim Patch Installer version 12.2.0.1.21
Copyright (c) 2020, Oracle Corporation.  All rights reserved.


Oracle Home       : /u01/app/19.3.0/grid
Central Inventory : /u01/app/oraInventory
   from           : /u01/app/19.3.0/grid/oraInst.loc
OPatch version    : 12.2.0.1.21
OUI version       : 12.2.0.7.0
Log file location : /u01/app/19.3.0/grid/cfgtoollogs/opatch/opatch2020-08-12_18-25-47PM_1.log

Lsinventory Output file location : /u01/app/19.3.0/grid/cfgtoollogs/opatch/lsinv/lsinventory2020-08-12_18-25-47PM.txt
--------------------------------------------------------------------------------
Local Machine Information::
Hostname: rac1-node1.raclab.local
ARU platform id: 226
ARU platform description:: Linux x86-64

Installed Top-level Products (1): 

Oracle Grid Infrastructure 19c                                       19.0.0.0.0
There are 1 products installed in this Oracle Home.


Interim patches (4) :

Patch  29585399     : applied on Thu Apr 18 08:36:24 BST 2019
Unique Patch ID:  22840393
Patch description:  "OCW RELEASE UPDATE 19.3.0.0.0 (29585399)"
   Created on 9 Apr 2019, 19:12:47 hrs PST8PDT
   Bugs fixed:
     27222128, 27572040, 27604329, 27760043, 27877830, 28302580, 28470673
     28621543, 28642469, 28699321, 28710663, 28755846, 28772816, 28785321
     28800508, 28808652, 28815557, 28847541, 28847572, 28870496, 28871040
     28874416, 28877252, 28881191, 28881848, 28888083, 28911140, 28925250
     28925460, 28935956, 28940472, 3, 28942694, 28951332, 28963036, 28968779
     28980448, 28995287, 29003207, 29003617, 29016294, 29018680, 29024876
     29026154, 29027933, 29047127, 29052850, 29058476, 29111631, 29112455
     29117337, 29123444, 29125708, 29125786, 29129476, 29131772, 29132456
     29139727, 29146157, 29147849, 29149170, 29152603, 29152752, 29154631
     29154636, 29154829, 29159216, 29159661, 29160462, 29161923, 29169540
     29169739, 29170717, 29173618, 29181568, 29182920, 29183298, 29186091
     29191827, 29201143, 29201695, 29209545, 29210577, 29210610, 29210624
     29210683, 29213641, 29219627, 29224294, 29225861, 29229839, 29235934
     29242906, 29243749, 29244495, 29244766, 29244968, 29248723, 29249583
     29251564, 29255616, 29260224, 29261695, 29271019, 29273360, 29282090
     29282666, 29285453, 29285621, 29290235, 29292232, 29293806, 29294753
     29299830, 29307090, 29307109, 29311336, 29329675, 29330791, 29339299
     29357821, 29360467, 29360775, 29367971, 29368725, 29379299, 29379381
     29380527, 29381000, 29382296, 29391301, 29393649, 29402110, 29411931
     29413360, 29457319, 29465047

Patch  29517247     : applied on Thu Apr 18 08:36:02 BST 2019
Unique Patch ID:  22840392
Patch description:  "ACFS RELEASE UPDATE 19.3.0.0.0 (29517247)"
   Created on 1 Apr 2019, 15:08:20 hrs PST8PDT
   Bugs fixed:
     28611527, 28687713, 28701011, 28740425, 28844788, 28860451, 28960047
     29031452, 29039918, 29115917, 29198743, 29264772

Patch  29517242     : applied on Thu Apr 18 08:35:39 BST 2019
Unique Patch ID:  22862832
Patch description:  "Database Release Update : 19.3.0.0.190416 (29517242)"
   Created on 17 Apr 2019, 23:27:10 hrs PST8PDT
   Bugs fixed:
     29515240, 14735102, 19697993, 20313356, 21965541, 25806201, 25883179
     25986062, 26476244, 26611353, 26872233, 27369515, 27423500, 27666312
     27710072, 27846298, 27957203, 28064977, 28072567, 28129791, 28181021
     28210681, 28279456, 28313275, 28350595, 28371123, 28379065, 28431445
     28463226, 28489419, 28502773, 28513333, 28534475, 28561704, 28569897
     28572533, 28572544, 28587723, 28593682, 28594086, 28597221, 28601957
     28605066, 28606598, 28625862, 28627033, 28636532, 28643718, 28644549
     28645570, 28646200, 28646939, 28649388, 28655209, 28663782, 28673945
     28692275, 28694872, 28696373, 28705231, 28710385, 28710734, 28714461
     28718469, 28730079, 28740708, 28760206, 28772390, 28774416, 28777214
     28789531, 28791852, 28795551, 28802734, 28804517, 28810381, 28811560
     28815123, 28815355, 28819640, 28824482, 28833912, 28835937, 28862532
     28863432, 28873575, 28876253, 28876639, 28884931, 28888327, 28892794
     28897512, 28899663, 28901126, 28905457, 28907196, 28912691, 28915561
     28917080, 28918429, 28919145, 28922227, 28922532, 28922608, 28925634
     28925880, 28933158, 28936114, 28937717, 28938698, 28940179, 28940281
     28941901, 28942455, 28945421, 28945994, 28951533, 28952168, 28954762
     28955606, 28957292, 28957723, 28962775, 28965231, 28966444, 28974083
     28977322, 28983095, 28983486, 28986326, 28986481, 28988482, 28989306
     28993295, 28994307, 28996376, 29000000, 29001888, 29002927, 29003738
     29006318, 29006621, 29007321, 29007775, 29008035, 29011936, 29013475
     29014076, 29015118, 29017265, 29018655, 29019121, 29021063, 29021352
     29024552, 29026582, 29026606, 29027456, 29027694, 29027940, 29031575
     29031600, 29032234, 29032457, 29032607, 29033052, 29033145, 29033200
     29033280, 29034587, 29037290, 29038528, 29039089, 29039510, 29043554
     29043651, 29043725, 29044763, 29044954, 29047850, 29048289, 29048498
     29048605, 29050560, 29050765, 29051702, 29052726, 29053783, 29056024
     29056270, 29056560, 29059011, 29061959, 29062692, 29062848, 29062860
     29062868, 29110526, 29110783, 29110790, 29110797, 29110802, 29110805
     29111598, 29113282, 29113305, 29117526, 29117642, 29119077, 29120223
     29122224, 29122254, 29123297, 29123432, 29123482, 29124368, 29125380
     29126345, 29127957, 29128935, 29129450, 29129497, 29129712, 29130219
     29131539, 29132938, 29134447, 29136111, 29138641, 29141316, 29141341
     29141685, 29142667, 29144995, 29145214, 29145730, 29149829, 29150338
     29151520, 29152357, 29155099, 29157389, 29158680, 29158899, 29159909
     29159936, 29160174, 29162095, 29163415, 29163437, 29163524, 29163567
     29167111, 29167342, 29167374, 29167940, 29168219, 29168433, 29169073
     29169215, 29171942, 29172618, 29172826, 29173140, 29173373, 29173817
     29174004, 29176318, 29177466, 29177543, 29177886, 29178385, 29180313
     29180455, 29180559, 29180893, 29181153, 29181231, 29181620, 29181743
     29181923, 29182019, 29183912, 29184297, 29184666, 29185193, 29186456
     29189302, 29189307, 29189889, 29190235, 29190474, 29190740, 29191541
     29192419, 29192468, 29192685, 29193207, 29194205, 29194367, 29194493
     29194827, 29195279, 29195337, 29195758, 29196725, 29199635, 29199733
     29200316, 29200700, 29201494, 29201539, 29202104, 29202850, 29203122
     29203166, 29203425, 29203443, 29203604, 29205281, 29205323, 29205419
     29205463, 29205767, 29205918, 29206109, 29206605, 29207073, 29208260
     29208732, 29211457, 29211724, 29212012, 29212433, 29212611, 29213351
     29213775, 29213850, 29213879, 29214561, 29214960, 29216746, 29216984
     29217294, 29217472, 29217828, 29217848, 29218570, 29219205, 29219273
     29220079, 29221248, 29221891, 29222031, 29222784, 29223833, 29223859
     29223967, 29224065, 29224605, 29225076, 29227602, 29228869, 29229164
     29229754, 29229844, 29229955, 29230252, 29230565, 29231133, 29232117
     29232154, 29234123, 29237538, 29240307, 29241345, 29242017, 29242884
     29243958, 29245137, 29245160, 29246163, 29247415, 29247712, 29247906
     29248552, 29248835, 29248858, 29249991, 29250059, 29251259, 29253184
     29253871, 29254031, 29254930, 29255178, 29255273, 29255431, 29255435
     29256426, 29259119, 29259320, 29261906, 29262512, 29262887, 29265448
     29266248, 29266899, 29267292, 29268412, 29269171, 29270585, 29273539
     29273735, 29273847, 29274428, 29274564, 29274627, 29275461, 29278218
     29279658, 29279751, 29279854, 29282898, 29285503, 29285788, 29285956
     29286037, 29287130, 29287705, 29292837, 29293072, 29297863, 29297915
     29298220, 29299049, 29299082, 29299844, 29301566, 29302963, 29303918
     29304781, 29311588, 29312310, 29312734, 29312753, 29313347, 29313417
     29313525, 29314539, 29318410, 29319441, 29321489, 29323946, 29324568
     29325087, 29325105, 29325257, 29325993, 29327044, 29329087, 29331209
     29331380, 29331493, 29332771, 29333500, 29337310, 29338315, 29338453
     29338780, 29338913, 29339155, 29341209, 29343086, 29346943, 29347620
     29348176, 29350052, 29351386, 29351716, 29351749, 29352867, 29353271
     29355654, 29356547, 29356752, 29358828, 29360672, 29361801, 29363151
     29364171, 29364177, 29367019, 29367561, 29368253, 29373418, 29373588
     29374179, 29377986, 29378029, 29379978, 29382784, 29385652, 29386502
     29386635, 29386660, 29387274, 29388094, 29388524, 29388830, 29389889
     29390435, 29394140, 29394749, 29397954, 29398863, 29399100, 29399121
     29405012, 29405651, 29412066, 29412269, 29417884, 29423826, 29429264
     29429566, 29431485, 29435652, 29438736, 29439522, 29450421, 29451386
     29452576, 29452953, 29457807, 29460252, 29462957, 29486181, 29507616
     29521748, 29530812, 29531654, 29557336, 29558975, 29601461

Patch  29401763     : applied on Thu Apr 18 08:35:16 BST 2019
Unique Patch ID:  22759421
Patch description:  "TOMCAT RELEASE UPDATE 19.0.0.0.0 (29401763)"
   Created on 11 Apr 2019, 22:26:25 hrs PST8PDT
   Bugs fixed:
     29286300



--------------------------------------------------------------------------------

OPatch succeeded.
[oracle@rac1-node1 ~]$ 
```

**Comment by Project-42** [comment]
ok, looks like the issue could be the remote argument, not sure if still available in opatchauto.
I added "set -x" in the script and found the command triggering the error:
```
[oracle@rac1-node1 scripts]$ ./lspatches.sh 
+ ALL_NODES=Yes
+ GREP=.
+ UNGREP=nothing_to_ungrep_unless_v_option_is_used15645
+ FILE=
+ OUT=
+ TMP=/tmp/fictemplspatches15645
+ TMP2=/tmp/fictemplspatches215645
+ SHOW_HOMES=NO
+ getopts lg:v:f:o:hsV OPT
++ uname
+ OS=Linux
+ case ${OS} in
+ ORATAB=/etc/oratab
++ which awk
+ AWK=/usr/bin/awk
+ '[' '!' -f /etc/oratab ']'
+ '[' '!' -f /usr/bin/awk ']'
+ [[ -n '' ]]
+ '[' NO = YES ']'
+ '[' '!' -f ']'
+ [[ -n '' ]]
++ ps -ef
++ grep pmon
++ grep asm
++ awk '{print $NF}'
++ sed s/asm_pmon_//
++ egrep '^[+]'
+ ORACLE_SID=+ASM1
+ '[' -z +ASM1 ']'
+ export ORAENV_ASK=NO
+ ORAENV_ASK=NO
+ . oraenv
+ '[' '!' -f /u01/app/19.3.0/grid/bin/olsnodes ']'
++ olsnodes
++ wc -l
+ [[ 2 -eq 0 ]]
+ '[' -z ']'
+ cat /dev/null
++ cat /etc/oratab
++ grep -v '^#'
++ grep -v '^$'
++ grep -v agent
++ awk 'BEGIN {FS=":"} { print $2}'
++ grep .
++ uniq
++ sort
++ grep -v nothing_to_ungrep_unless_v_option_is_used15645
+ for OH in '`cat ${ORATAB} | grep -v "^#" | grep -v "^$" | grep -v agent | awk '\''BEGIN {FS=":"} { print $2}'\'' | grep ${GREP} | grep -v ${UNGREP} | sort | uniq`'
+ printf %-80s 'Proceeding with /u01/app/19.3.0/grid . . .'
Proceeding with /u01/app/19.3.0/grid . . .                                      + '[' -f /u01/app/19.3.0/grid/OPatch/opatch ']'
+ '[' -x /u01/app/19.3.0/grid/OPatch/opatch ']'
++ /u01/app/19.3.0/grid/OPatch/opatch version
++ grep Version
++ awk '{print $NF}'
+ OPATCH_DOTTED_VERSION=12.2.0.1.21
+ ERR=0
+ '[' 0 -eq 0 ']'
++ echo 12.2.0.1.21
++ sed 's/\.//g'
+ OPATCH_VERSION=1220121
+ [[ 12 -eq 12 ]]
+ [[ 1220121 -gt 1220112 ]]
+ '[' Yes = Yes ']'
+ ALL_NODES_OPTION=' -remote '
+ echo 'Oracle Interim Patch Installer version 12.2.0.1.21'
+ /u01/app/19.3.0/grid/OPatch/opatchauto report -type patches -format xml -remote
+ ERR=41
+ '[' 41 -eq 0 ']'
+ printf '\t\033[1;31m%-8s' 'Error 41'
	Error 41+ cat /tmp/fictemplspatches215645
+ printf '\033[m\n' ''
[.......]
```

And then I tried the command directly:
```
[oracle@rac1-node1 ~]$ /u01/app/19.3.0/grid/OPatch/opatchauto report -type patches -format xml -remote

OPatchauto session is initiated at Wed Aug 12 18:45:11 2020

System initialization log file is /u01/app/19.3.0/grid/cfgtoollogs/opatchautodb/systemconfig2020-08-12_06-45-11PM.log.

OPATCHAUTO-68029: Invalid argument.
OPATCHAUTO-68029: The argument specified is invalid: -remote
OPATCHAUTO-68029: Verify the arguments provided on the command line.

Oracle OPatchAuto Version 13.9.4.4.0
Copyright (c) 2016, Oracle Corporation.  All rights reserved.

DESCRIPTION
    This operation generates report.

[..]

OPatchauto session completed at Wed Aug 12 18:45:26 2020
Time taken to complete the session 0 minute, 16 seconds

 opatchauto failed with error code 41
[oracle@rac1-node1 ~]$ 
```

**Comment by freddenis** [comment]
> Having this issue in a 2 nodes RAC system (no Exadata) Opatch is 12.2.0.1.21
> 
> -- Full error output:
> 
> ```
> [oracle@rac1-node1 scripts]$ ./lspatches.sh
> Proceeding with /u01/app/19.3.0/grid . . .                                        Error 41
> Proceeding with /u01/app/oracle/product/11.2.0/dbhome_1 . . .                     Error 41print() on closed filehandle $FileHandler at /u01/app/oracle/product/11.2.0/dbhome_1/OPatch/auto/database/bin/module/DBUtilServices.pm line 508.
> 
> Proceeding with /u01/app/oracle/product/12.1.0/dbhome_1 . . .                     Error 41print() on closed filehandle $FileHandler at /u01/app/oracle/product/12.1.0/dbhome_1/OPatch/auto/database/bin/module/DBUtilServices.pm line 508.
> 
> Proceeding with /u01/app/oracle/product/12.2.0/dbhome_1 . . .                     Error 41print() on closed filehandle $FileHandler at /u01/app/oracle/product/12.2.0/dbhome_1/OPatch/auto/database/bin/module/DBUtilServices.pm line 508.
> 
> Proceeding with /u01/app/oracle/product/18.0.0/dbhome_1 . . .                     Error 41print() on closed filehandle $FileHandler at /u01/app/oracle/product/18.0.0/dbhome_1/OPatch/auto/database/bin/module/DBUtilServices.pm line 508.
> 
> Proceeding with /u01/app/oracle/product/19.3.0/dbhome_1 . . .                     Error 41
> 
> [oracle@rac1-node1 scripts]$ 
> ```
> 
> -- If I force local, works fine, so wondering something fails in my "cluster inventory" (ssh keys are shared):
> 
> ```
> [oracle@rac1-node1 scripts]$ ./lspatches.sh -l
> Proceeding with /u01/app/19.3.0/grid . . .                                        OK      
> Proceeding with /u01/app/oracle/product/11.2.0/dbhome_1 . . .                     OK      
> Proceeding with /u01/app/oracle/product/12.1.0/dbhome_1 . . .                     OK      
> Proceeding with /u01/app/oracle/product/12.2.0/dbhome_1 . . .                     OK      
> Proceeding with /u01/app/oracle/product/18.0.0/dbhome_1 . . .                     OK      
> Proceeding with /u01/app/oracle/product/19.3.0/dbhome_1 . . .                     OK      
> 
>   /u01/app/19.3.0/grid  (opatch version 12.2.0.1.21)
> ------------------------------
>   Patch ID  |   rac1-node1   |
> ------------------------------
>   29401763  |        -       |
>   29517242  |        -       |
>   29517247  |        -       |
>   29585399  |        -       |
> ------------------------------
> 
>   /u01/app/oracle/product/11.2.0/dbhome_1  (opatch version 12.2.0.1.21)
> ------------------------------
>   Patch ID  |   rac1-node1   |
> ------------------------------
>      No patch installed      |
> ------------------------------
> 
>   /u01/app/oracle/product/12.1.0/dbhome_1  (opatch version 12.2.0.1.21)
> ------------------------------
>   Patch ID  |   rac1-node1   |
> ------------------------------
>      No patch installed      |
> ------------------------------
> 
>   /u01/app/oracle/product/12.2.0/dbhome_1  (opatch version 12.2.0.1.21)
> ------------------------------
>   Patch ID  |   rac1-node1   |
> ------------------------------
>   26327418  |        -       |
> ------------------------------
> 
>   /u01/app/oracle/product/18.0.0/dbhome_1  (opatch version 12.2.0.1.21)
> ------------------------------
>   Patch ID  |   rac1-node1   |
> ------------------------------
>   27908644  |        -       |
>   27923415  |        -       |
>   28090523  |        -       |
>   28090553  |        -       |
> ------------------------------
> 
>   /u01/app/oracle/product/19.3.0/dbhome_1  (opatch version 12.2.0.1.21)
> ------------------------------
>   Patch ID  |   rac1-node1   |
> ------------------------------
>   29517242  |        -       |
>   29585399  |        -       |
> ------------------------------
> 
> [oracle@rac1-node1 scripts]$
> ```
> 
> -- ASM inventory example
> 
> ```
> [oracle@rac1-node1 ~]$ . oraenv
> ORACLE_SID = [oracle] ? +ASM1
> The Oracle base has been set to /u01/app/grid
> [oracle@rac1-node1 ~]$ $ORACLE_HOME/OPatch/opatch lsinventory
> Oracle Interim Patch Installer version 12.2.0.1.21
> Copyright (c) 2020, Oracle Corporation.  All rights reserved.
> 
> 
> Oracle Home       : /u01/app/19.3.0/grid
> Central Inventory : /u01/app/oraInventory
>    from           : /u01/app/19.3.0/grid/oraInst.loc
> OPatch version    : 12.2.0.1.21
> OUI version       : 12.2.0.7.0
> Log file location : /u01/app/19.3.0/grid/cfgtoollogs/opatch/opatch2020-08-12_18-25-47PM_1.log
> 
> Lsinventory Output file location : /u01/app/19.3.0/grid/cfgtoollogs/opatch/lsinv/lsinventory2020-08-12_18-25-47PM.txt
> --------------------------------------------------------------------------------
> Local Machine Information::
> Hostname: rac1-node1.raclab.local
> ARU platform id: 226
> ARU platform description:: Linux x86-64
> 
> Installed Top-level Products (1): 
> 
> Oracle Grid Infrastructure 19c                                       19.0.0.0.0
> There are 1 products installed in this Oracle Home.
> 
> 
> Interim patches (4) :
> 
> Patch  29585399     : applied on Thu Apr 18 08:36:24 BST 2019
> Unique Patch ID:  22840393
> Patch description:  "OCW RELEASE UPDATE 19.3.0.0.0 (29585399)"
>    Created on 9 Apr 2019, 19:12:47 hrs PST8PDT
>    Bugs fixed:
>      27222128, 27572040, 27604329, 27760043, 27877830, 28302580, 28470673
>      28621543, 28642469, 28699321, 28710663, 28755846, 28772816, 28785321
>      28800508, 28808652, 28815557, 28847541, 28847572, 28870496, 28871040
>      28874416, 28877252, 28881191, 28881848, 28888083, 28911140, 28925250
>      28925460, 28935956, 28940472, 3, 28942694, 28951332, 28963036, 28968779
>      28980448, 28995287, 29003207, 29003617, 29016294, 29018680, 29024876
>      29026154, 29027933, 29047127, 29052850, 29058476, 29111631, 29112455
>      29117337, 29123444, 29125708, 29125786, 29129476, 29131772, 29132456
>      29139727, 29146157, 29147849, 29149170, 29152603, 29152752, 29154631
>      29154636, 29154829, 29159216, 29159661, 29160462, 29161923, 29169540
>      29169739, 29170717, 29173618, 29181568, 29182920, 29183298, 29186091
>      29191827, 29201143, 29201695, 29209545, 29210577, 29210610, 29210624
>      29210683, 29213641, 29219627, 29224294, 29225861, 29229839, 29235934
>      29242906, 29243749, 29244495, 29244766, 29244968, 29248723, 29249583
>      29251564, 29255616, 29260224, 29261695, 29271019, 29273360, 29282090
>      29282666, 29285453, 29285621, 29290235, 29292232, 29293806, 29294753
>      29299830, 29307090, 29307109, 29311336, 29329675, 29330791, 29339299
>      29357821, 29360467, 29360775, 29367971, 29368725, 29379299, 29379381
>      29380527, 29381000, 29382296, 29391301, 29393649, 29402110, 29411931
>      29413360, 29457319, 29465047
> 
> Patch  29517247     : applied on Thu Apr 18 08:36:02 BST 2019
> Unique Patch ID:  22840392
> Patch description:  "ACFS RELEASE UPDATE 19.3.0.0.0 (29517247)"
>    Created on 1 Apr 2019, 15:08:20 hrs PST8PDT
>    Bugs fixed:
>      28611527, 28687713, 28701011, 28740425, 28844788, 28860451, 28960047
>      29031452, 29039918, 29115917, 29198743, 29264772
> 
> Patch  29517242     : applied on Thu Apr 18 08:35:39 BST 2019
> Unique Patch ID:  22862832
> Patch description:  "Database Release Update : 19.3.0.0.190416 (29517242)"
>    Created on 17 Apr 2019, 23:27:10 hrs PST8PDT
>    Bugs fixed:
>      29515240, 14735102, 19697993, 20313356, 21965541, 25806201, 25883179
>      25986062, 26476244, 26611353, 26872233, 27369515, 27423500, 27666312
>      27710072, 27846298, 27957203, 28064977, 28072567, 28129791, 28181021
>      28210681, 28279456, 28313275, 28350595, 28371123, 28379065, 28431445
>      28463226, 28489419, 28502773, 28513333, 28534475, 28561704, 28569897
>      28572533, 28572544, 28587723, 28593682, 28594086, 28597221, 28601957
>      28605066, 28606598, 28625862, 28627033, 28636532, 28643718, 28644549
>      28645570, 28646200, 28646939, 28649388, 28655209, 28663782, 28673945
>      28692275, 28694872, 28696373, 28705231, 28710385, 28710734, 28714461
>      28718469, 28730079, 28740708, 28760206, 28772390, 28774416, 28777214
>      28789531, 28791852, 28795551, 28802734, 28804517, 28810381, 28811560
>      28815123, 28815355, 28819640, 28824482, 28833912, 28835937, 28862532
>      28863432, 28873575, 28876253, 28876639, 28884931, 28888327, 28892794
>      28897512, 28899663, 28901126, 28905457, 28907196, 28912691, 28915561
>      28917080, 28918429, 28919145, 28922227, 28922532, 28922608, 28925634
>      28925880, 28933158, 28936114, 28937717, 28938698, 28940179, 28940281
>      28941901, 28942455, 28945421, 28945994, 28951533, 28952168, 28954762
>      28955606, 28957292, 28957723, 28962775, 28965231, 28966444, 28974083
>      28977322, 28983095, 28983486, 28986326, 28986481, 28988482, 28989306
>      28993295, 28994307, 28996376, 29000000, 29001888, 29002927, 29003738
>      29006318, 29006621, 29007321, 29007775, 29008035, 29011936, 29013475
>      29014076, 29015118, 29017265, 29018655, 29019121, 29021063, 29021352
>      29024552, 29026582, 29026606, 29027456, 29027694, 29027940, 29031575
>      29031600, 29032234, 29032457, 29032607, 29033052, 29033145, 29033200
>      29033280, 29034587, 29037290, 29038528, 29039089, 29039510, 29043554
>      29043651, 29043725, 29044763, 29044954, 29047850, 29048289, 29048498
>      29048605, 29050560, 29050765, 29051702, 29052726, 29053783, 29056024
>      29056270, 29056560, 29059011, 29061959, 29062692, 29062848, 29062860
>      29062868, 29110526, 29110783, 29110790, 29110797, 29110802, 29110805
>      29111598, 29113282, 29113305, 29117526, 29117642, 29119077, 29120223
>      29122224, 29122254, 29123297, 29123432, 29123482, 29124368, 29125380
>      29126345, 29127957, 29128935, 29129450, 29129497, 29129712, 29130219
>      29131539, 29132938, 29134447, 29136111, 29138641, 29141316, 29141341
>      29141685, 29142667, 29144995, 29145214, 29145730, 29149829, 29150338
>      29151520, 29152357, 29155099, 29157389, 29158680, 29158899, 29159909
>      29159936, 29160174, 29162095, 29163415, 29163437, 29163524, 29163567
>      29167111, 29167342, 29167374, 29167940, 29168219, 29168433, 29169073
>      29169215, 29171942, 29172618, 29172826, 29173140, 29173373, 29173817
>      29174004, 29176318, 29177466, 29177543, 29177886, 29178385, 29180313
>      29180455, 29180559, 29180893, 29181153, 29181231, 29181620, 29181743
>      29181923, 29182019, 29183912, 29184297, 29184666, 29185193, 29186456
>      29189302, 29189307, 29189889, 29190235, 29190474, 29190740, 29191541
>      29192419, 29192468, 29192685, 29193207, 29194205, 29194367, 29194493
>      29194827, 29195279, 29195337, 29195758, 29196725, 29199635, 29199733
>      29200316, 29200700, 29201494, 29201539, 29202104, 29202850, 29203122
>      29203166, 29203425, 29203443, 29203604, 29205281, 29205323, 29205419
>      29205463, 29205767, 29205918, 29206109, 29206605, 29207073, 29208260
>      29208732, 29211457, 29211724, 29212012, 29212433, 29212611, 29213351
>      29213775, 29213850, 29213879, 29214561, 29214960, 29216746, 29216984
>      29217294, 29217472, 29217828, 29217848, 29218570, 29219205, 29219273
>      29220079, 29221248, 29221891, 29222031, 29222784, 29223833, 29223859
>      29223967, 29224065, 29224605, 29225076, 29227602, 29228869, 29229164
>      29229754, 29229844, 29229955, 29230252, 29230565, 29231133, 29232117
>      29232154, 29234123, 29237538, 29240307, 29241345, 29242017, 29242884
>      29243958, 29245137, 29245160, 29246163, 29247415, 29247712, 29247906
>      29248552, 29248835, 29248858, 29249991, 29250059, 29251259, 29253184
>      29253871, 29254031, 29254930, 29255178, 29255273, 29255431, 29255435
>      29256426, 29259119, 29259320, 29261906, 29262512, 29262887, 29265448
>      29266248, 29266899, 29267292, 29268412, 29269171, 29270585, 29273539
>      29273735, 29273847, 29274428, 29274564, 29274627, 29275461, 29278218
>      29279658, 29279751, 29279854, 29282898, 29285503, 29285788, 29285956
>      29286037, 29287130, 29287705, 29292837, 29293072, 29297863, 29297915
>      29298220, 29299049, 29299082, 29299844, 29301566, 29302963, 29303918
>      29304781, 29311588, 29312310, 29312734, 29312753, 29313347, 29313417
>      29313525, 29314539, 29318410, 29319441, 29321489, 29323946, 29324568
>      29325087, 29325105, 29325257, 29325993, 29327044, 29329087, 29331209
>      29331380, 29331493, 29332771, 29333500, 29337310, 29338315, 29338453
>      29338780, 29338913, 29339155, 29341209, 29343086, 29346943, 29347620
>      29348176, 29350052, 29351386, 29351716, 29351749, 29352867, 29353271
>      29355654, 29356547, 29356752, 29358828, 29360672, 29361801, 29363151
>      29364171, 29364177, 29367019, 29367561, 29368253, 29373418, 29373588
>      29374179, 29377986, 29378029, 29379978, 29382784, 29385652, 29386502
>      29386635, 29386660, 29387274, 29388094, 29388524, 29388830, 29389889
>      29390435, 29394140, 29394749, 29397954, 29398863, 29399100, 29399121
>      29405012, 29405651, 29412066, 29412269, 29417884, 29423826, 29429264
>      29429566, 29431485, 29435652, 29438736, 29439522, 29450421, 29451386
>      29452576, 29452953, 29457807, 29460252, 29462957, 29486181, 29507616
>      29521748, 29530812, 29531654, 29557336, 29558975, 29601461
> 
> Patch  29401763     : applied on Thu Apr 18 08:35:16 BST 2019
> Unique Patch ID:  22759421
> Patch description:  "TOMCAT RELEASE UPDATE 19.0.0.0.0 (29401763)"
>    Created on 11 Apr 2019, 22:26:25 hrs PST8PDT
>    Bugs fixed:
>      29286300
> 
> 
> 
> --------------------------------------------------------------------------------
> 
> OPatch succeeded.
> [oracle@rac1-node1 ~]$ 
> ```

This is an opatch issue. On top of that, this script has been replaced by the better https://unknowndba.blogspot.com/2021/05/list-ohpatches-sh-better-oracle-patch-reporting-tool.html
