### ISSUE TITLE
rac-status.sh : DB output if first 4 characters of db name is same as cluster

### ISSUE THREAD

**Issue by scott-colesays** [freddenis/oracle-scripts#16]
Cluster "crsxeg7"
DB shows "n_637", but should show "xeg7n_637"

Maybe it's me...
![github_rac-status sh](https://user-images.githubusercontent.com/111466975/185255137-8a5ccc36-c2c8-4026-b864-f09155008b1e.jpg)

**Comment by freddenis** [comment]
> 
Thanks Scott, could you please do:

./rac-status.sh -a -o fileforfred.txt

And send me this file by email (my email is on top of the script); I'll check to fix this.

Thanks,

**Comment by freddenis** [comment]
Fixed in version 20221222
