### ISSUE TITLE
exa-howsmart crashes if HCC isn't enabled

### ISSUE THREAD

**Issue by slords** [freddenis/oracle-scripts#9]
I receive the following error when running howsmart.  We don't have HCC enabled and it appears to crash when trying to calculate the percentages.

awk: cmd. line:99: (FILENAME=/tmp/exastats240299.tmp FNR=3886) fatal: division by zero attempted

**Comment by freddenis** [comment]
Hi,

FYI, This one is still on dev.

I have no 12.2 with no HCC so I cannot test myself -- I made a quick fix, could you please let me know ? if not I'll have to find a way for real test cases.

Thanks,

**Comment by slords** [comment]
Confirmed working.
